#!/bin/bash
LOG_DIR=logs

function print_status { 
    status=$1
    if [ $status == 0 ];then
       echo "${Green}Ok${NC}" 
    else
       echo "${Red}Failed${NC}"
    fi
}

function log {
   message=$1
   logfile=$2
   echo -n $message
   echo -n $message > ${LOG_DIR}/${logfile}
}

. ~/bin/bash_colors.sh 
virtualenv ./demo
. demo/bin/activate
mkdir -p $LOG_DIR 
log "Installing jupyter with pip..." jupyter_install.log
pip install jupyter >> $LOG_DIR/jupyter_install.log
status=$?
print_status $status

log "Installing icgc with pip..." icgc_install.log
pip install icgc >> $LOG_DIR/icgc_install.log
print_status $status

if [ $status == 0 ];then
   log "Starting jupyter notebook" jupyter.log
   jupyter notebook
   print_status $?
else
  log "${Red}Installation failed.${NC}"
fi
