# docker
- name: "create docker volume: '{{ item }}'"
  shell: "docker volume inspect {{ item }} >/dev/null 2>&1 || docker volume create --name {{ item }}"
  with_items: [ "{{ opt_volume }}" ]

- name: "Pull docker volume image"
  shell: "docker pull {{create_volume_image}}"

- name: "Pull notebook image"
  shell: "docker pull {{notebook_image}}"

- name: Run bash so that the mount will copy the mount directory into the volume
  shell: "docker run -v \"{{opt_volume}}:/opt\" {{create_volume_image}} /bin/bash"
