# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "2"

services:
  hub:
    #build:
    #  context: "{{ build_dir }}/hub"
    #  args:
    #    JUPYTERHUB_VERSION: {{ jupyterhub_version }}
    #    USE_OAUTH: "{{ use_oauth }}" 
    restart: {{ restart_policy }} 
    image: {{ jupyterhub_image }} 
    container_name: {{ container_name }} 
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "{{ docker_socket}}:{{ jupyterhub_socket }}:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "data:{{ data_mount_point }}"
      - "{{ share_dir }}:{{ share_mount }}"
      {{ config }}
    ports:
      - "{{ jupyterhub_port }}:{{ jupyterhub_port }}"
    command: >
      jupyterhub -f /srv/jupyterhub/config/jupyterhub_config.py

volumes:
  data:
    external:
      name: {{ data_volume }}

networks:
  default:
    external:
      name: {{ docker_network_name }}
