- name: Install requirements for certbot 
  become: true
  become_user: root 
  apt:
    update_cache: yes 
    name: software-properties-common 

- name: Add certbot repository to apt
  become: true
  become_user: root
  apt_repository:
    repo: ppa:certbot/certbot 
    state: present

- name: Install certbot 
  become: true
  become_user: root 
  apt:
    update_cache: yes 
    name: certbot 

- name: Run certbot to create a SSL certificate for our server 
  become: true
  become_user: root
  shell: "test -d {{ certbot_dir }} || certbot certonly -d {{ host }} --agree-tos --email {{ certbot_email }} --standalone -q"
  ignore_errors: true

- name: Create our config dir if it doesn't exist
  become: true
  become_user: "{{ jukebox_user }}"
  shell: "test -d {{ config_dir }} || mkdir {{ config_dir }}"

- name: Copy the certificates into our config dir 
  become: true
  become_user: root
  shell: "cp {{ certbot_dir }}/*.pem {{ config_dir }}"
